### PR TITLE
(REPLATS-514) Do not purge WEAVE-CANARY filrewallchains

### PR DESCRIPTION
**Pull request by jpartlow**
The WEAVE-CANARY firewallchains in filter, mangle and nat tables were
not in our list of Kubernetes managed firewallchains not to merge. I
think skipping them was just an oversight, and this patches that.

### CODE REVIEW

**Comment by jpartlow** [comment]
The kurl_test::configure_firewall plan is failing when attempting to remove the WEAVE-CANARY:filter chain.

```
Err: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:filter:IPv4]/ensure: change from 'present' to 'absent' failed: Execution of '/usr/sbin/iptables -t filter -X WEAVE-CANARY' returned 1: iptables: No chain/target/match by that name.
```

I don't know why. The chain exists prior to the plan running.

Full log:

```
  Notice: /Stage[main]/Firewall::Linux::Redhat/Package[iptables-services]/ensure: created
  Notice: /Stage[main]/Firewall::Linux::Redhat/Exec[/usr/bin/systemctl daemon-reload]: Triggered 'refresh' from 1 event
  Notice: /Stage[main]/Firewall::Linux::Redhat/Service[iptables]/ensure: ensure changed 'stopped' to 'running'
  Notice: /Stage[main]/Firewall::Linux::Redhat/Service[nftables]/ensure: ensure changed 'stopped' to 'running'
  Notice: /Stage[main]/Firewall::Linux::Redhat/Service[ip6tables]/ensure: ensure changed 'stopped' to 'running'
  Notice: /Stage[main]/Main/Firewall[000 accept all icmp]/ensure: created
  Notice: /Stage[main]/Main/Firewall[001 accept all to lo interface]/ensure: created
  Notice: /Stage[main]/Main/Firewall[002 accept related established rules]/ensure: created
  Notice: /Stage[main]/Main/Firewall[003 accept inbound SSH]/ensure: created
  Notice: /Stage[main]/Main/Firewall[100 allow responding on established connections]/ensure: created
  Notice: /Stage[main]/Main/Firewall[100 allow communication on loopback addresses]/ensure: created
  Notice: /Stage[main]/Main/Firewall[100 allow communication in private networks]/ensure: created
  Warning: Firewallchain[PREROUTING:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain PREROUTING:nat:IPv4
  Notice: /Stage[main]/Main/Firewallchain[PREROUTING:nat:IPv4]/ensure: removed
  Warning: Firewallchain[INPUT:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain INPUT:nat:IPv4
  Notice: /Stage[main]/Main/Firewallchain[INPUT:nat:IPv4]/ensure: removed
  Warning: Firewallchain[POSTROUTING:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain POSTROUTING:nat:IPv4
  Notice: /Stage[main]/Main/Firewallchain[POSTROUTING:nat:IPv4]/ensure: removed
  Warning: Firewallchain[OUTPUT:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain OUTPUT:nat:IPv4
  Notice: /Stage[main]/Main/Firewallchain[OUTPUT:nat:IPv4]/ensure: removed
  Notice: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:nat:IPv4]/ensure: removed
  Err: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:filter:IPv4]/ensure: change from 'present' to 'absent' failed: Execution of '/usr/sbin/iptables -t filter -X WEAVE-CANARY' returned 1: iptables: No chain/target/match by that name.
  Warning: Firewallchain[PREROUTING:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain PREROUTING:mangle:IPv4
  Notice: /Stage[main]/Main/Firewallchain[PREROUTING:mangle:IPv4]/ensure: removed
  Warning: Firewallchain[INPUT:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain INPUT:mangle:IPv4
  Notice: /Stage[main]/Main/Firewallchain[INPUT:mangle:IPv4]/ensure: removed
  Warning: Firewallchain[FORWARD:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain FORWARD:mangle:IPv4
  Notice: /Stage[main]/Main/Firewallchain[FORWARD:mangle:IPv4]/ensure: removed
  Warning: Firewallchain[OUTPUT:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain OUTPUT:mangle:IPv4
  Notice: /Stage[main]/Main/Firewallchain[OUTPUT:mangle:IPv4]/ensure: removed
  Warning: Firewallchain[POSTROUTING:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain POSTROUTING:mangle:IPv4
  Notice: /Stage[main]/Main/Firewallchain[POSTROUTING:mangle:IPv4]/ensure: removed
  Notice: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:mangle:IPv4]/ensure: removed
  Notice: /Stage[main]/Pam_firewall/Firewallchain[CNI-HOSTPORT-MASQ:nat:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[CNI-HOSTPORT-SETMARK:nat:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[DOCKER-ISOLATION-STAGE-1:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[DOCKER-ISOLATION-STAGE-2:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[DOCKER-USER:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[DOCKER:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[DOCKER:nat:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[KUBE-FIREWALL:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[KUBE-FORWARD:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[KUBE-KUBELET-CANARY:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[WEAVE-IPSEC-IN:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[WEAVE-NPC-DEFAULT:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[WEAVE-NPC-EGRESS-ACCEPT:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[WEAVE-NPC-EGRESS-CUSTOM:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[WEAVE-NPC-EGRESS-DEFAULT:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewallchain[WEAVE-NPC-INGRESS:filter:IPv4]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow tcp port 8800 for Admin Console UI]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow tcp app ports]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow tcp port 6443 for Kubernetes API]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow tcp port 2379-2380 from 10.16.112.74 for etcd]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow tcp port 6783 from 10.16.112.74 for Weave]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow udp ports 6783-6784 from 10.16.112.74 for Weave]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow tcp port 10250 from 10.16.112.74 for Kubelet]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow pod network]/ensure: created
  Notice: /Stage[main]/Pam_firewall/Firewall[110 allow service network]/ensure: created
  Notice: /Stage[main]/Main/Firewall[999 log remaining input]/ensure: created
  Notice: /Stage[main]/Main/Firewall[999 log remaining output]/ensure: created
  Notice: /Stage[main]/Main/Firewall[999 log remaining forward]/ensure: created
  Notice: /Stage[main]/Main/Firewallchain[INPUT:filter:IPv4]/policy: policy changed 'accept' to 'drop'
  Notice: /Stage[main]/Main/Firewallchain[OUTPUT:filter:IPv4]/policy: policy changed 'accept' to 'drop'
  Notice: /Stage[main]/Main/Firewallchain[FORWARD:filter:IPv4]/policy: policy changed 'accept' to 'drop'
  changed: 54, failed: 1, unchanged: 22 skipped: 0, noop: 0
```

When re-run, it succeeds:

Full log:
```
  Warning: Firewallchain[PREROUTING:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain PREROUTING:nat:IPv4                                                                                                                                                
  Notice: /Stage[main]/Main/Firewallchain[PREROUTING:nat:IPv4]/ensure: removed                                                                                                                                                                                                  
  Warning: Firewallchain[INPUT:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain INPUT:nat:IPv4                                                                                                                                                          
  Notice: /Stage[main]/Main/Firewallchain[INPUT:nat:IPv4]/ensure: removed                                                                                                                                                                                                       
  Warning: Firewallchain[POSTROUTING:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain POSTROUTING:nat:IPv4                                                                                                                                              
  Notice: /Stage[main]/Main/Firewallchain[POSTROUTING:nat:IPv4]/ensure: removed                                                                                                                                                                                                 
  Warning: Firewallchain[OUTPUT:nat:IPv4](provider=iptables_chain): Attempting to destroy internal chain OUTPUT:nat:IPv4                                                                                                                                                        
  Notice: /Stage[main]/Main/Firewallchain[OUTPUT:nat:IPv4]/ensure: removed                                                                                                                                                                                                     
  Notice: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:nat:IPv4]/ensure: removed                                                                                                                                                                                                
  Warning: Firewallchain[PREROUTING:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain PREROUTING:mangle:IPv4                                                                                                                                          
  Notice: /Stage[main]/Main/Firewallchain[PREROUTING:mangle:IPv4]/ensure: removed                                                                                                                                                                                               
  Warning: Firewallchain[INPUT:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain INPUT:mangle:IPv4                                                                                                                                                    
  Notice: /Stage[main]/Main/Firewallchain[INPUT:mangle:IPv4]/ensure: removed                                                                                                                                                                                                    
  Warning: Firewallchain[FORWARD:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain FORWARD:mangle:IPv4                                                                                                                                                
  Notice: /Stage[main]/Main/Firewallchain[FORWARD:mangle:IPv4]/ensure: removed                                                                                                                                                                                                  
  Warning: Firewallchain[OUTPUT:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain OUTPUT:mangle:IPv4                                                                                                                                                  
  Notice: /Stage[main]/Main/Firewallchain[OUTPUT:mangle:IPv4]/ensure: removed                                                                                                                                                                                                   
  Warning: Firewallchain[POSTROUTING:mangle:IPv4](provider=iptables_chain): Attempting to destroy internal chain POSTROUTING:mangle:IPv4                                                                                                                                        
  Notice: /Stage[main]/Main/Firewallchain[POSTROUTING:mangle:IPv4]/ensure: removed                                                                                                                                                                                              
  Notice: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:mangle:IPv4]/ensure: removed                                                                                                                                                                                             
  Notice: /Stage[main]/Main/Firewallchain[WEAVE-CANARY:filter:IPv4]/ensure: removed                                                                                                                                                                                             
  Warning: Firewallchain[INPUT:filter:IPv6](provider=iptables_chain): Attempting to destroy internal chain INPUT:filter:IPv6                                                                                                                                                    
  Notice: /Stage[main]/Main/Firewallchain[INPUT:filter:IPv6]/ensure: removed                                                                                                                                                                                                    
  Warning: Firewallchain[FORWARD:filter:IPv6](provider=iptables_chain): Attempting to destroy internal chain FORWARD:filter:IPv6                                                                                                                                                
  Notice: /Stage[main]/Main/Firewallchain[FORWARD:filter:IPv6]/ensure: removed                                                                                                                                                                                                  
  Warning: Firewallchain[OUTPUT:filter:IPv6](provider=iptables_chain): Attempting to destroy internal chain OUTPUT:filter:IPv6                                                                                                                                                  
  Notice: /Stage[main]/Main/Firewallchain[OUTPUT:filter:IPv6]/ensure: removed                                                                                                                                                                                                   
  changed: 15, failed: 0, unchanged: 65 skipped: 0, noop: 0
```

So, it's puzzling.

I assume that pam_firewall's firwallchain list of chains to avoid purging should be updated to include WEAVE-CANARY, and that we never noticed this previously because centos-8.3-kurl-beta would configure the firewall before restarting k8s. The WEAVE-CANARY chains do exist in the centos-8.3-kurl-beta image. I don't know why the first run would fail and the second succeed.

But kurl_test airgap testing with redhat-8.4-kurl-beta vm does pass with this patch. I'll be updating puppetlabs/kurl_test#48 in a moment to run with this branch.

**Review by MikaelSmith — APPROVED** [review]
This seems like a reasonable addition.

**Comment by jpartlow** [comment]
Oh, there was one other peculiarity I noticed when reading the README for pam_firewall. It mentions passing preserve-iptables-config when installing PAM, which is not something we're doing in https://github.com/puppetlabs/puppetlabs-packer/blob/master/scripts/kurl.sh#L42, if that needs to change.  Although it didn't seem to matter before, and we're now applying the firewall resources after pam is installed and running :shrug:

**Comment by MikaelSmith** [comment]
That worked in our tests because we would:

1. Install kURL. At this point no special iptables config exists.
2. Shutdown kubelet.
3. Start a new machine from the image.
4. Set up firewall rules, which also starts the iptables service.
5. Reconfigure Kubernetes and start kubelet.

Kubernetes startup is where all the iptables rules get written. And kURL installer isn't run after our custom iptables config, so nothing to preserve during install.

**Comment by jpartlow** [comment]
Oh I see, it's purely the kurl install script's interaction with iptables, so even though kubernetes gets restarted now before we run the firewall_config plan, it has no bearing for our vm.

**Comment by jpartlow** [comment]
puppetlabs/kurl_test#48 is passing with this change.

**Pull request merged**
